"""Initial migration: create country tables

Revision ID: 5b4e3b1e5d96
Revises: 
Create Date: 2026-04-15 15:26:02.706127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4e3b1e5d96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_datos_paises_id'), 'datos_paises', ['id'], unique=False)
    op.drop_constraint('fk_pais', 'datos_paises', type_='foreignkey')
    op.create_foreign_key(None, 'datos_paises', 'paises', ['pais_id'], ['id'])
    op.create_index(op.f('ix_metricas_etl_id'), 'metricas_etl', ['id'], unique=False)
    op.create_index(op.f('ix_paises_id'), 'paises', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paises_id'), table_name='paises')
    op.drop_index(op.f('ix_metricas_etl_id'), table_name='metricas_etl')
    op.drop_constraint(None, 'datos_paises', type_='foreignkey')
    op.create_foreign_key('fk_pais', 'datos_paises', 'paises', ['pais_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_datos_paises_id'), table_name='datos_paises')
    # ### end Alembic commands ###
